version: '3'


services:
  db:
    image: postgres:12.9
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
      DATABASE_ROOT_USERNAME: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_APP_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://fusionauth:9011
    restart: unless-stopped
    ports:
      - "9011:9011"
    volumes:
      - fusionauth_config:/usr/local/fusionauth/config
  questions:
    build:
      context: ./questions
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - fusionauth
      - telegram
    environment:
      TZ: Asia/Yekaterinburg
      FUSIONAUTH_DOMAIN: http://fusionauth:9011
      FUSIONAUTH_TOKEN: ${QUESTIONS_FUSIONAUTH_TOKEN}
      TELEGRAM_API: http://telegram:3000
      QUESTIONS_URL: http://questions:3000


    volumes:
      - q_data:/app/data
  telegram:
    build:
      context: ./telegram
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - fusionauth
    environment:
      FUSIONAUTH_DOMAIN: http://fusionauth:9011
      FUSIONAUTH_TOKEN: ${TELEGRAM_FUSIONAUTH_TOKEN}
      TG_TOKEN: ${TG_TOKEN}

    volumes:
      - tg_data:/app/data
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    depends_on:
      - fusionauth
    environment:
      FUSIONAUTH_DOMAIN: http://fusionauth:9011
      FUSIONAUTH_TOKEN: ${WEB_FUSIONAUTH_TOKEN}
      FUSIONAUTH_CLIENT_ID: ${FUSIONAUTH_CLIENT_ID}
      FUSIONAUTH_CLIENT_SECRET: ${FUSIONAUTH_CLIENT_SECRET}
      QUESTIONS_URL: http://questions:3000
    volumes:
      - web_data:/app/data

volumes:
  db_data:
  fusionauth_config:
  q_data:
  tg_data:
  web_data:
